### ISSUE TITLE
Block collection blocks reference lib-franklin.js instead of aem.js

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/helix-block-collection#16]
### Expected Behaviour

I expect to be able to copy block collection code from the project, and paste it into my project generated from the latest boilerplate and have the copied code work.

### Actual Behaviour

Copied code does not work as it continues to reference `lib-franklin.js` instead of the newly named `aem.js`.

### Workaround

Rename `lib-franklin.js` in the copied block to `aem.js` however newer developers may not know the history of this file or understand why/where its coming from, and possibly even copy `lib-franklin.js` from this project into their own project!

#### Steps to Reproduce

1. Generate a new project from latest boilerplate
2. Copy the fragment.js from this project into the new project
3. You will receive an error that fragment.js cannot find lib-franklin.js

#### Platform and Version

Effects any project generate from boilerplate after release of: https://github.com/adobe/aem-boilerplate/commit/f5ab4df26a992f70a123f56b08062f7dc0b47dae#diff-0e7c120a93e71c8d3532a0952c7ca07331340900de8e45b33ff1d1f1eb72b674

#### Sample Code that illustrates the problem

N/A 

#### Logs taken while reproducing problem

`fragment.js:13     GET http://localhost:3000/scripts/lib-franklin.js net::ERR_ABORTED 404 (Not Found)`

**Comment by shsteimer** [comment]
@davidjgonzalez think this was closed by https://github.com/adobe/helix-block-collection/pull/18

if not feel free to re-open
